version: "3.1"
services:
    www:
        build: .
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: motohelp
            MYSQL_PASSWORD: frombrothertobrotherwithwhengetmeout1001
            MYSQL_ROOT_PASSWORD: frombrothertobrotherwithwhengetmeout1001
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
